//! Machine-file (`.mach`) format v2 verification, driven by server-produced
//! fixtures.
//!
//! Every `.machine` file under `tests/fixtures/machine-file-v2/` came out of
//! `tamga-api`'s own `encode_machine_file`. Nothing here is generated by this
//! crate, and that is the whole point: for two years each SDK tested its
//! machine-file verifier against a file it had built itself, so every fixture
//! faithfully reproduced that SDK's own misreading of the wire format. CI
//! stayed green while nothing the server actually emitted could be opened.
//!
//! These tests **iterate `manifest.json`** rather than naming fixtures, so
//! additional schemes and variants extend coverage by being dropped into the
//! directory with a manifest entry — no edit here.
//!
//! Unit coverage of the same verifier against synthesised inputs lives in
//! `src/checkout/machine_file.rs::tests`; it exercises branches (missing key,
//! malformed PEM) that a captured artefact cannot. It does not replace this
//! file, and this file does not replace it.

use base64::Engine as _;
use std::collections::BTreeMap;
use std::path::PathBuf;
use tamga::checkout::machine_file::{verify_machine_file, verify_machine_file_at};
use tamga::error::{CheckoutError, CryptoError};
use tamga::models::policy::LicenseScheme;

const B64: base64::engine::GeneralPurpose = base64::engine::general_purpose::STANDARD;

/// The earliest representable instant. Evaluating a file here proves it is
/// authentic and parseable without any expiry verdict getting in the way —
/// every captured fixture's `exp` is far in this timestamp's future.
const BEFORE_ANY_FIXTURE_WAS_ISSUED: i64 = 0;

/// Mirrors `CLOCK_SKEW_TOLERANCE_SECS` in `src/checkout/license_file.rs`,
/// which the machine-file path reuses. Kept as a literal here on purpose: if
/// the constant is ever widened, these tests must notice rather than move with
/// it.
const EXPECTED_SKEW_TOLERANCE_SECS: i64 = 60;

// ── manifest ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, serde::Deserialize)]
struct Fixture {
    #[serde(default)]
    file: Option<String>,
    alg: String,
    encrypted: bool,
    #[serde(default)]
    enc_is_dot_separated: Option<bool>,
    public_key_b64: String,
    kid: String,
    license_key: Option<String>,
    fingerprint: String,
    expired: bool,
    scheme: String,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/machine-file-v2")
}

/// Every manifest entry, ordered by name so failures read the same way twice.
fn manifest() -> BTreeMap<String, Fixture> {
    let path = fixtures_dir().join("manifest.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let parsed: BTreeMap<String, Fixture> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert!(
        !parsed.is_empty(),
        "the fixture manifest is empty — these tests would vacuously pass"
    );
    parsed
}

impl Fixture {
    fn pem(&self, name: &str) -> String {
        let file = self
            .file
            .clone()
            .unwrap_or_else(|| format!("{name}.machine"));
        let path = fixtures_dir().join(&file);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", path.display()))
    }

    fn pubkey(&self) -> Vec<u8> {
        B64.decode(&self.public_key_b64)
            .expect("manifest public_key_b64 is not valid base64")
    }

    /// The governing licence's scheme. Accepts the wire spelling
    /// (`ED25519_SIGN`) and the Rust variant name (`Ed25519Sign`) so the
    /// manifest can be written either way.
    fn scheme(&self) -> LicenseScheme {
        LicenseScheme::parse(&self.scheme)
            .or(match self.scheme.as_str() {
                "Ed25519Sign" => Some(LicenseScheme::Ed25519Sign),
                "Rsa2048Pkcs1Sign" => Some(LicenseScheme::Rsa2048Pkcs1Sign),
                "Rsa2048Pkcs1PssSign" => Some(LicenseScheme::Rsa2048Pkcs1PssSign),
                "EcdsaP256Sign" => Some(LicenseScheme::EcdsaP256Sign),
                "Rsa2048JwtRs256" => Some(LicenseScheme::Rsa2048JwtRs256),
                _ => None,
            })
            .unwrap_or_else(|| panic!("unknown scheme {:?} in the manifest", self.scheme))
    }

    fn license_key(&self) -> Option<&str> {
        self.license_key.as_deref()
    }
}

// ── certificate surgery, for the negative cases ──────────────────────────────

/// The inner `{ enc, sig, alg }` object, unwrapped from the PEM envelope.
fn cert_of(pem: &str) -> serde_json::Value {
    let body: String = pem.lines().filter(|l| !l.starts_with("-----")).collect();
    let json = B64
        .decode(body.trim())
        .expect("fixture PEM body is not base64");
    serde_json::from_slice(&json).expect("fixture PEM body is not { enc, sig, alg } JSON")
}

/// Re-wraps a mutated certificate back into a PEM envelope. `sig` covers only
/// `enc`, so editing `alg` leaves a genuinely well-signed file — exactly the
/// downgrade an attacker would attempt.
fn repack(pem: &str, mutate: impl FnOnce(&mut serde_json::Value)) -> String {
    let mut cert = cert_of(pem);
    mutate(&mut cert);
    let body = B64.encode(serde_json::to_string(&cert).unwrap().as_bytes());
    format!("-----BEGIN MACHINE FILE-----\n{body}\n-----END MACHINE FILE-----")
}

// ── the wire format the server actually produces ─────────────────────────────

#[test]
fn every_fixture_declares_the_alg_the_manifest_records() {
    for (name, fx) in manifest() {
        let cert = cert_of(&fx.pem(&name));
        assert_eq!(
            cert["alg"].as_str().unwrap(),
            fx.alg,
            "{name}: certificate alg drifted from the manifest"
        );
        assert!(
            fx.alg.ends_with("+v2"),
            "{name}: the server always emits the +v2 marker"
        );
    }
}

#[test]
fn an_encrypted_enc_is_two_separately_base64_encoded_halves() {
    // `FieldEncryption::encrypt` returns `format!("{nonce_b64}.{cipher_b64}")`.
    // The server's own doc comment above `encode_machine_file` says
    // `base64(nonce‖ciphertext‖tag)` and is wrong — it contradicts the code it
    // documents, and every SDK implemented the comment. Both halves are
    // separately padded to a multiple of four, so a lenient decoder skips the
    // `.` and rebuilds the right bytes by accident; Rust's engine is strict and
    // refuses, which the last assertion below pins down.
    let mut seen_encrypted = false;
    for (name, fx) in manifest() {
        let cert = cert_of(&fx.pem(&name));
        let enc = cert["enc"].as_str().unwrap();
        if let Some(expected) = fx.enc_is_dot_separated {
            assert_eq!(
                enc.contains('.'),
                expected,
                "{name}: enc_is_dot_separated disagrees with the fixture"
            );
        }
        if !fx.encrypted {
            assert!(!enc.contains('.'), "{name}: a plain enc is one base64 blob");
            continue;
        }
        seen_encrypted = true;
        let (nonce_b64, cipher_b64) = enc
            .split_once('.')
            .unwrap_or_else(|| panic!("{name}: encrypted enc is not dot-separated"));
        assert_eq!(
            B64.decode(nonce_b64)
                .expect("nonce half is not base64")
                .len(),
            12,
            "{name}: AES-256-GCM nonce is 12 bytes"
        );
        assert!(
            B64.decode(cipher_b64)
                .expect("ciphertext half is not base64")
                .len()
                > 16,
            "{name}: ciphertext must exceed the bare 16-byte GCM tag"
        );
        // Strict engine: `.` is not in the base64 alphabet, so the
        // single-blob read this crate used to do cannot even get off the
        // ground. A lenient decoder would skip it and land on the right bytes
        // by accident — which is exactly how the same misreading stayed
        // invisible in the SDKs whose decoders are permissive.
        assert!(
            B64.decode(enc).is_err(),
            "{name}: the whole enc string is NOT one base64 blob — decoding it \
             as one is the bug this fixture exists to catch"
        );
    }
    assert!(
        seen_encrypted,
        "the manifest carries no encrypted fixture — the AES-GCM path is untested"
    );
}

// ── the happy path ───────────────────────────────────────────────────────────

#[test]
fn every_fixture_verifies_under_its_own_scheme_and_key() {
    for (name, fx) in manifest() {
        let verified = verify_machine_file_at(
            &fx.pem(&name),
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .unwrap_or_else(|e| panic!("{name}: a genuine server-issued file failed to verify: {e}"));

        assert_eq!(
            verified.machine.attributes.fingerprint, fx.fingerprint,
            "{name}: decoded the wrong machine"
        );
        assert_eq!(verified.claims.kid, fx.kid, "{name}: unexpected kid claim");
        assert!(
            !verified.claims.jti.is_empty(),
            "{name}: jti claim is empty"
        );
        assert!(verified.claims.iat > 0, "{name}: iat claim is not set");
    }
}

#[test]
fn the_system_clock_entry_point_refuses_a_long_expired_fixture() {
    // `verify_machine_file` reads the system clock, so it can only be pointed
    // at files that are expired now and always will be. Every captured fixture
    // qualifies; the ones the manifest marks `expired` are the ones whose
    // expiry is meaningful at their own `iat` too.
    let mut seen = 0usize;
    for (name, fx) in manifest().into_iter().filter(|(_, f)| f.expired) {
        seen += 1;
        let err = verify_machine_file(
            &fx.pem(&name),
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
        )
        .expect_err("a captured fixture is long past its exp against the real clock");
        assert!(
            matches!(err, CheckoutError::Expired { .. }),
            "{name}: expected Expired from the system-clock entry point, got {err:?}"
        );
    }
    assert!(
        seen > 0,
        "no fixture is marked expired — the system-clock path is untested"
    );
}

// ── M3: the signed exp claim ─────────────────────────────────────────────────

#[test]
fn the_signed_exp_claim_decides_the_verdict_at_the_files_own_issue_time() {
    for (name, fx) in manifest() {
        let pem = fx.pem(&name);
        let issued = verify_machine_file_at(
            &pem,
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .unwrap_or_else(|e| panic!("{name}: {e}"))
        .claims
        .iat;

        let at_issue_time = verify_machine_file_at(
            &pem,
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            issued,
        );

        if fx.expired {
            let err = at_issue_time
                .err()
                .unwrap_or_else(|| panic!("{name}: an expired file verified anyway"));
            assert!(
                matches!(err, CheckoutError::Expired { .. }),
                "{name}: expiry must be distinguishable from a forged file, got {err:?}"
            );
        } else {
            at_issue_time.unwrap_or_else(|e| panic!("{name}: a live file was rejected: {e}"));
        }
    }
}

#[test]
fn exp_is_enforced_with_a_sixty_second_skew_tolerance() {
    let mut checked = 0usize;
    for (name, fx) in manifest() {
        let pem = fx.pem(&name);
        let verify_at = |now: i64| {
            verify_machine_file_at(
                &pem,
                fx.scheme(),
                &fx.pubkey(),
                fx.license_key(),
                Some(&fx.fingerprint),
                now,
            )
        };
        let Some(exp) = verify_at(BEFORE_ANY_FIXTURE_WAS_ISSUED)
            .unwrap_or_else(|e| panic!("{name}: {e}"))
            .claims
            .exp
        else {
            // A checkout made without a `ttl` legitimately has no `exp` and
            // genuinely never expires. Absence is not an error.
            continue;
        };
        checked += 1;

        verify_at(exp).unwrap_or_else(|e| panic!("{name}: rejected exactly at exp: {e}"));
        verify_at(exp + EXPECTED_SKEW_TOLERANCE_SECS - 1)
            .unwrap_or_else(|e| panic!("{name}: rejected inside the skew tolerance: {e}"));

        let err = verify_at(exp + EXPECTED_SKEW_TOLERANCE_SECS + 1)
            .expect_err("past exp plus the tolerance the file must be refused");
        assert!(
            matches!(err, CheckoutError::Expired { exp: e } if e == exp),
            "{name}: expected Expired{{exp: {exp}}}, got {err:?}"
        );
        // A generous allowance would just be a free extension on every expired
        // file, since the clock belongs to the attacker.
        assert!(
            verify_at(exp + 3600).is_err(),
            "{name}: an hour past exp must not still verify"
        );
    }
    assert!(
        checked > 0,
        "no fixture carried an exp claim — expiry enforcement is untested"
    );
}

// ── M1: the +v2 marker and the alg cross-check ───────────────────────────────

#[test]
fn a_file_whose_alg_lacks_the_v2_marker_is_rejected() {
    // v1 carried no `meta.exp` inside the signed payload and derived its AES
    // key by zero-padding the licence key instead of through HKDF. Accepting
    // one silently reinstates both weaknesses — and the signature still checks
    // out, because `sig` covers `enc` alone.
    for (name, fx) in manifest() {
        let downgraded = repack(&fx.pem(&name), |cert| {
            let v1 = fx.alg.trim_end_matches("+v2").to_string();
            cert["alg"] = serde_json::json!(v1);
        });
        let err = verify_machine_file_at(
            &downgraded,
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("a v1 alg must be refused outright");
        assert!(
            matches!(err, CheckoutError::UnsupportedAlgorithm(_)),
            "{name}: expected UnsupportedAlgorithm, got {err:?}"
        );
    }
}

#[test]
fn a_v3_or_padded_marker_is_not_mistaken_for_v2() {
    // A substring `contains("+v2")` test — how several sibling SDKs pass this
    // by accident — would wave all three of these through.
    for (name, fx) in manifest() {
        for forged in [
            fx.alg.replace("+v2", "+v3"),
            format!("{}junk", fx.alg),
            format!("x{}", fx.alg),
        ] {
            let repacked = repack(&fx.pem(&name), |cert| {
                cert["alg"] = serde_json::json!(forged);
            });
            let result = verify_machine_file_at(
                &repacked,
                fx.scheme(),
                &fx.pubkey(),
                fx.license_key(),
                Some(&fx.fingerprint),
                BEFORE_ANY_FIXTURE_WAS_ISSUED,
            );
            let err = result
                .err()
                .unwrap_or_else(|| panic!("{name}: forged alg {forged:?} was accepted"));
            assert!(
                matches!(err, CheckoutError::UnsupportedAlgorithm(_)),
                "{name}: expected UnsupportedAlgorithm for {forged:?}, got {err:?}"
            );
        }
    }
}

#[test]
fn the_alg_suffix_is_cross_checked_against_the_caller_supplied_scheme() {
    for (name, fx) in manifest() {
        let wrong = match fx.scheme() {
            LicenseScheme::Ed25519Sign => LicenseScheme::EcdsaP256Sign,
            LicenseScheme::EcdsaP256Sign => LicenseScheme::Ed25519Sign,
            LicenseScheme::Rsa2048Pkcs1Sign => LicenseScheme::Rsa2048Pkcs1PssSign,
            LicenseScheme::Rsa2048Pkcs1PssSign => LicenseScheme::Rsa2048Pkcs1Sign,
            LicenseScheme::Rsa2048JwtRs256 => continue,
        };
        let err = verify_machine_file_at(
            &fx.pem(&name),
            wrong,
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("a scheme whose suffix does not match the file must be refused");
        assert!(
            matches!(err, CheckoutError::UnsupportedAlgorithm(_)),
            "{name}: expected UnsupportedAlgorithm for {wrong:?}, got {err:?}"
        );
    }
}

#[test]
fn rsa_sha256_cannot_identify_the_scheme_so_the_caller_stays_authoritative() {
    // The server emits the identical `rsa-sha256` suffix for
    // `RSA_2048_PKCS1_SIGN` and `RSA_2048_JWT_RS256`. Same bytes, same `alg`,
    // two different verdicts decided entirely by the caller-supplied scheme —
    // which is why `alg` must never be allowed to select the primitive.
    let mut seen = 0usize;
    for (name, fx) in manifest() {
        if fx.scheme() != LicenseScheme::Rsa2048Pkcs1Sign {
            continue;
        }
        seen += 1;
        let pem = fx.pem(&name);
        assert!(
            fx.alg.contains("+rsa-sha256+"),
            "{name}: expected the ambiguous rsa-sha256 suffix"
        );

        verify_machine_file_at(
            &pem,
            LicenseScheme::Rsa2048Pkcs1Sign,
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .unwrap_or_else(|e| panic!("{name}: PKCS#1 is the real scheme and must verify: {e}"));

        let err = verify_machine_file_at(
            &pem,
            LicenseScheme::Rsa2048JwtRs256,
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("RSA_2048_JWT_RS256 is refused for machine files");
        assert!(
            matches!(err, CheckoutError::SchemeNotSupported),
            "{name}: expected SchemeNotSupported, got {err:?}"
        );
    }
    assert!(
        seen > 0,
        "no RSA-PKCS#1 fixture — the suffix-ambiguity case is untested"
    );
}

#[test]
fn rsa_jwt_rs256_is_refused_before_anything_is_parsed() {
    for (name, fx) in manifest() {
        let err = verify_machine_file_at(
            "not a PEM envelope at all",
            LicenseScheme::Rsa2048JwtRs256,
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("JWT scheme is refused");
        assert!(
            matches!(err, CheckoutError::SchemeNotSupported),
            "{name}: rejection must precede parsing, got {err:?}"
        );
    }
}

// ── M2: decryption, and the order operations happen in ───────────────────────

#[test]
fn a_tampered_enc_fails_the_signature_before_any_decode_or_decrypt() {
    // The suffix makes `enc` invalid base64 and, for an encrypted file, breaks
    // the `<nonce>.<cipher>` split too. If either decode ran first the error
    // would be InvalidBase64 or DecryptionFailed. It must be the signature —
    // attacker-controlled bytes are never decoded before they are authenticated.
    for (name, fx) in manifest() {
        let tampered = repack(&fx.pem(&name), |cert| {
            let enc = cert["enc"].as_str().unwrap().to_string();
            cert["enc"] = serde_json::json!(format!("{enc}!!!"));
        });
        let err = verify_machine_file_at(
            &tampered,
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("a tampered enc must not verify");
        assert!(
            matches!(err, CheckoutError::Crypto(CryptoError::VerificationFailed)),
            "{name}: expected a signature failure, got {err:?}"
        );
    }
}

#[test]
fn the_wrong_fingerprint_fails_decryption() {
    let mut seen = 0usize;
    for (name, fx) in manifest().into_iter().filter(|(_, f)| f.encrypted) {
        seen += 1;
        let err = verify_machine_file_at(
            &fx.pem(&name),
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            Some("not-this-machines-fingerprint"),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("a machine file is bound to one fingerprint");
        assert!(
            matches!(err, CheckoutError::Crypto(CryptoError::DecryptionFailed)),
            "{name}: expected DecryptionFailed, got {err:?}"
        );
    }
    assert!(seen > 0, "no encrypted fixture to bind-check");
}

#[test]
fn the_wrong_licence_key_fails_decryption() {
    let mut seen = 0usize;
    for (name, fx) in manifest().into_iter().filter(|(_, f)| f.encrypted) {
        seen += 1;
        let err = verify_machine_file_at(
            &fx.pem(&name),
            fx.scheme(),
            &fx.pubkey(),
            Some("TAMGA-NOT-THE-RIGHT-LICENCE-KEY"),
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("the HKDF ikm is the licence key");
        assert!(
            matches!(err, CheckoutError::Crypto(CryptoError::DecryptionFailed)),
            "{name}: expected DecryptionFailed, got {err:?}"
        );
    }
    assert!(seen > 0, "no encrypted fixture to key-check");
}

#[test]
fn decrypting_needs_both_the_licence_key_and_the_fingerprint() {
    let mut seen = 0usize;
    for (name, fx) in manifest().into_iter().filter(|(_, f)| f.encrypted) {
        seen += 1;
        let pem = fx.pem(&name);
        let missing_key = verify_machine_file_at(
            &pem,
            fx.scheme(),
            &fx.pubkey(),
            None,
            Some(&fx.fingerprint),
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("no licence key");
        assert!(
            matches!(missing_key, CheckoutError::LicenseKeyMissing),
            "{name}: expected LicenseKeyMissing, got {missing_key:?}"
        );

        let missing_fp = verify_machine_file_at(
            &pem,
            fx.scheme(),
            &fx.pubkey(),
            fx.license_key(),
            None,
            BEFORE_ANY_FIXTURE_WAS_ISSUED,
        )
        .expect_err("no fingerprint");
        assert!(
            matches!(missing_fp, CheckoutError::FingerprintMissing),
            "{name}: expected FingerprintMissing, got {missing_fp:?}"
        );
    }
    assert!(
        seen > 0,
        "no encrypted fixture — the missing-credential branches are untested"
    );
}

#[test]
fn another_accounts_key_does_not_verify() {
    // Cross-product over the manifest: every fixture against every other
    // fixture's public key. Only the matching pair may verify.
    let all = manifest();
    for (name, fx) in &all {
        for (other_name, other) in &all {
            if other.public_key_b64 == fx.public_key_b64 {
                continue;
            }
            let result = verify_machine_file_at(
                &fx.pem(name),
                fx.scheme(),
                &other.pubkey(),
                fx.license_key(),
                Some(&fx.fingerprint),
                BEFORE_ANY_FIXTURE_WAS_ISSUED,
            );
            assert!(
                result.is_err(),
                "{name} verified under {other_name}'s public key"
            );
        }
    }
}
